version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - USER_AGENT=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
      - CRAWLER_TIMEOUT=30
      - REQUEST_TIMEOUT=60 